#-----------------------------------------------------------------------------------------------------------------
# Example configuration for exposing spinnaker with ingress (requires ingress.yml).
#
# Operator populates automatically "overrideBaseUrl" settings taking the public spinnaker urls from the
# ingress definition, and also adjusts gate's context path so that target rewrite is not required in the ingress.
#-----------------------------------------------------------------------------------------------------------------
apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  expose:
    type: ingress  # Spinnaker is exposed using ingress. Available options: service, ingress
  config:
    security:
      apiSecurity:
        overrideBaseUrl: https://spinnaker.mycompany.com/api  # Public API (Gate) url. Using the same hostname for deck and gate only works when exposing spinnaker with ingress.
      uiSecurity:
        overrideBaseUrl: https://spinnaker.mycompany.com     # Public UI (Deck) url.
  profiles:
    gate:
      server:
        servlet:
          context-path: /api
  service-settings:
    gate:
      healthEndpoint: /api/health