#-----------------------------------------------------------------------------------------------------------------
# Example configuration for using SQL as a caching store for clouddriver.
#
# Documentation: https://spinnaker.io/setup/productionize/persistence/clouddriver-sql/
#-----------------------------------------------------------------------------------------------------------------
apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  spinnakerConfig:
    profiles:
      clouddriver:
        sql:
          enabled: true
          taskRepository:
            enabled: true
          cache:
            enabled: true
            # These parameters were determined to be optimal via benchmark comparisons
            # in the Netflix production environment with Aurora. Setting these too low
            # or high may negatively impact performance. These values may be sub-optimal
            # in some environments.
            readBatchSize: 500
            writeBatchSize: 300
          scheduler:
            enabled: false # disabled for Google CloudSQL and Amazon Managed RDS SQL https://spinnaker.io/setup/productionize/persistence/clouddriver-sql/#agent-scheduling
          connectionPools:
            default:
              # additional connection pool parameters are available here,
              # for more detail and to view defaults, see:
              # https://github.com/spinnaker/kork/blob/master/kork-sql/src/main/kotlin/com/netflix/spinnaker/kork/sql/config/ConnectionPoolProperties.kt
              default: true
              jdbcUrl: jdbc:mysql://mysql:3306/clouddriver?useSSL=false&useUnicode=true&characterEncoding=utf8&connectionCollation=utf8mb4_unicode_ci # useUnicode and utf8 makes sure the database can store an emoji if one is ever added to the database
              user: clouddriver_service
              password: encrypted:k8s!n:spin-secrets!k:mysqlCdPassword  # (Secret). Depending on db auth and how spinnaker secrets are managed
            # The following tasks connection pool is optional. At Netflix, clouddriver
            # instances pointed to Aurora read replicas have a tasks pool pointed at the
            # master. Instances where the default pool is pointed to the master omit a
            # separate tasks pool.
            tasks:
              user: clouddriver_service
              password: encrypted:k8s!n:spin-secrets!k:mysqlCdPassword  # (Secret). Depending on db auth and how spinnaker secrets are managed
              jdbcUrl: jdbc:mysql://mysql:3306/clouddriver?useSSL=false&useUnicode=true&characterEncoding=utf8&connectionCollation=utf8mb4_unicode_ci # useUnicode and utf8 makes sure the database can store an emoji if one is ever added to the database
          migration:
            user: clouddriver_migrate
            password: encrypted:k8s!n:spin-secrets!k:mysqlCdMigratePassword  # (Secret). Depending on db auth and how spinnaker secrets are managed
            jdbcUrl: jdbc:mysql://mysql:3306/clouddriver?useSSL=false&useUnicode=true&characterEncoding=utf8&connectionCollation=utf8mb4_unicode_ci # useUnicode and utf8 makes sure the database can store an emoji if one is ever added to the database
        
        dualTaskRepository: # Maintaining Task Repository Availability While Migrating from Redis to SQL in production https://spinnaker.io/setup/productionize/persistence/clouddriver-sql/#maintaining-task-repository-availability-while-migrating-from-redis-to-sql
          enabled: false
          primaryClass: com.netflix.spinnaker.clouddriver.sql.SqlTaskRepository
          previousClass: com.netflix.spinnaker.clouddriver.data.task.jedis.RedisTaskRepository
        
        redis:
          enabled: true                   # only required if using externally managed redis AND Google CloudSQL or Amazon Managed RDS SQL
          # connection: redis://redis:6379  # only required if using externally managed redis AND Google CloudSQL or Amazon Managed RDS SQL
          cache:
            enabled: false
          scheduler:
            enabled: true # enabled for Google CloudSQL and Amazon Managed RDS SQL https://spinnaker.io/setup/productionize/persistence/clouddriver-sql/#agent-scheduling
          taskRepository:
            enabled: false
