#-------------------------------------------------------------------------------
# Minimum Starting Point Recipe with Armory Scale Agent.
#
# Self contained Spinnaker installation with no external dependencies and no
# additional configuration needed. This is intended as a starting point for any
# kubernetes cluster. Not for production use.
#
# Features:
# - Spinnaker Operator
# - One Kubernetes account (Spinnaker's own cluster) using the Scale Agent
# - Spinnaker authentication disabled
# - Self hosted minio as a persistent storage
# - Self hosted redis backend for caching and temporal storage of services
#-------------------------------------------------------------------------------
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spinnaker

resources:
  - infrastructure/mysql.yml           # (Optional, not for production use). MySQL server needed if using SQL backend in Spinnaker

components:  
  - core/base                             # Defines base configuration across the cluster
  - core/persistence/in-cluster           # Enables persistence using MinIO in-cluster
  - targets/kubernetes/scale-agent        # Enables the plugin version of the Scale Agent

patchesStrategicMerge:
  - core/patches/version.yml          # Sets the OSS version to use  
  - persistence/patch-sql-clouddriver.yml # setup clouddriver to use SQL for storage

transformers:
  - utilities/unique-service-account.yml  # Ensures that ServiceAccounts are unique  