#-----------------------------------------------------------------------------------------------------------------------
# Quick Start recipe
#
# Self contained Spinnaker installation with no external dependencies and no additional configuration needed.
# Not for production use.
#
# Features:
# - One Kubernetes account (Spinnaker's own cluster) for deployment targets
# - One dockerhub account for public repositories
# - Spinnaker authentication disabled
# - Spinnaker exposed out of the cluster using 2 public Kubernetes service load balancers
# - Self hosted minio as a persistent storage
# - Self hosted redis backend for caching and temporal storage of services
#-----------------------------------------------------------------------------------------------------------------------
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spinnaker

components:
  - core/base
  - core/persistence/in-cluster
  - targets/kubernetes/default

patchesStrategicMerge:
  - core/patches/version.yml
  - expose/patch-lb.yml                 # Automatically expose spinnaker
  - accounts/docker/patch-dockerhub.yml # Docker accounts
