{
 "title": "Spinnaker - main",
 "description": "Overall health of all Spinnaker services",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Selected Service",
    "query": "gate,orca,clouddriver,clouddriver_caching,clouddriver_ro,clouddriver_rw,clouddriver_ro_deck,front50,echo,igor,rosco,terraformer,dinghy"
   }
  ]
 },
 "panels": [
  { "title": "Common metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "-> $service controller latency by controller / method",
   "type": "graph",
   "description": "Ideal value: Latency below 5 seconds.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate($service:controller:invocations__max_total[1m])) by (controller, method) * 1000",
     "legendFormat": "{{controller}}/{{method}}"
    }
   ]
  },
  {
   "title": "Outgoing $service requests latency by requestHost ->",
   "type": "graph",
   "description": "Ideal value: Latency below 5 seconds.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate($service:okhttp:requests__max_total[1m])) by (requestHost) * 1000",
     "legendFormat": "{{requestHost}}"
    }
   ]
  },
  {
   "title": "<- $service 2xx returned by controller / method",
   "type": "graph",
   "description": "Ideal value: Any value.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "avg/second" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate($service:controller:invocations__count_total{status=\"2xx\"}[1m])) by (controller, method, statusCode), \"controller\", \"$1\", \"controller\", \"(.*)Controller\")",
     "legendFormat": "{{statusCode}}/{{controller}}/{{method}}"
    }
   ]
  },
  {
   "title": "$service 2xx received by requestHost <-",
   "type": "graph",
   "description": "Ideal value: Any value.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "avg/second" }
   ],
   "targets": [
    {
     "expr": "sum(rate($service:okhttp:requests__count_total{status=\"2xx\"}[1m])) by (requestHost)",
     "legendFormat": "{{requestHost}}"
    }
   ]
  },
  {
   "title": "<- $service 5xx errors returned by controller / method",
   "type": "graph",
   "description": "Ideal value: Chart empty at all times.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "avg/second" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate($service:controller:invocations__count_total{status=\"5xx\"}[1m])) by (controller, method, statusCode), \"controller\", \"$1\", \"controller\", \"(.*)Controller\")",
     "legendFormat": "{{statusCode}}/{{controller}}/{{method}}"
    }
   ]
  },
  {
   "title": "$service 5xx errors received by requestHost <-",
   "type": "graph",
   "description": "Ideal value: Chart empty at all times.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "avg/second" }
   ],
   "targets": [
    {
     "expr": "sum(rate($service:okhttp:requests__count_total{status=\"5xx\"}[1m])) by (requestHost)",
     "legendFormat": "{{requestHost}}"
    }
   ]
  },
  {
   "title": "$service CPU by instance",
   "type": "graph",
   "description": "Ideal value: Chart empty at all times.\nA \"success\" fallback means that the original request failed and a fallback behavior was executed. A \"failed\" fallback means that both, original and fallback behaviors failed. A \"circuitOpen\" means sustained failures causing fallbacks.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum($service:system:cpu:usage__value) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "$service JVM memory usage by instance",
   "type": "graph",
   "description": "Ideal value: below half the total memory available to pod.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum($service:jvm:memory:used__value{area=\"heap\"}) by (exported_instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Clouddriver specific metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "$service Avg Agent Time",
   "type": "graph",
   "description": "Ideal value: Below 1 minute.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(label_replace(\n  $service:executionTime__max_total{}\n, \"agentType\", \"$1\", \"agent\", \"^.*/(\\\\w+)\\\\[.*$\")\n) by (agentType)",
     "legendFormat": "{{agentType}}"
    }
   ]
  },
  {
   "title": "$service SQL objects written by type",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(clouddriver:cats:sqlCache:merge:itemCount__count_total[5m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "$service Kubernetes Number of Agents",
   "type": "graph",
   "description": "Ideal value: Any constant value.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(label_replace(\n  delta($service:executionTime__total{}[1m])\n, \"agentType\", \"$1\", \"agent\", \"^.*/(\\\\w+)\\\\[.*$\")\n) by (agentType)",
     "legendFormat": "{{agentType}}"
    }
   ]
  },
  {
   "title": "$service kubectl latency by account",
   "type": "graph",
   "description": "Ideal value: Below 5 seconds.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate($service:kubernetes:api__max_total{success=\"true\"}[1m])) by (account) * 10",
     "legendFormat": "{{account}}"
    }
   ]
  },
  {
   "title": "$service AWS Number of Agents",
   "type": "graph",
   "description": "Ideal value: Any constant value.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(label_replace(\n  delta($service:executionTime__totalTime_total{}[1m])\n, \"agentType\", \"$1\", \"agent\", \"^.*/(\\\\w+)\\\\[.*$\")\n) by (agent)",
     "legendFormat": "{{agent}}"
    }
   ]
  },
  {
   "title": "$service AWS failed requests by error / requestType",
   "type": "graph",
   "description": "Ideal value: Always 0.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short", "label": "avg/second" }
   ],
   "targets": [
    {
     "expr": "sum(rate($service:aws:request:requestCount_total{error=\"true\"}[1m])) by (AWSErrorCode, requestType)",
     "legendFormat": "{{AWSErrorCode}}/{{requestType}}"
    }
   ]
  },
  {
   "title": "SQL objects written by type",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(clouddriver:cats:sqlCache:merge:itemCount__count_total[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "$service AWS successful requests by requestType",
   "type": "graph",
   "description": "Ideal value: Any value.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short", "label": "avg/second" }
   ],
   "targets": [
    {
     "expr": "sum(rate($service:aws:request:requestCount_total{error=\"false\"}[1m])) by (requestType)",
     "legendFormat": "{{requestType}}"
    }
   ]
  },
  {
   "title": "$service sql tasks connection pool",
   "type": "graph",
   "description": "Ideal value: 0 blocked, below 30 active.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "$service:sql:pool:tasks:total{}",
     "legendFormat": "total/{{instance}}"
    },
    {
     "expr": "$service:sql:pool:tasks:active{}",
     "legendFormat": "active/{{instance}}"
    },
    {
     "expr": "$service:sql:pool:tasks:blocked{}",
     "legendFormat": "blocked/{{instance}}"
    }
   ]
  },
  {
   "title": "$service sql default connection pool",
   "type": "graph",
   "description": "Ideal value: 0 blocked, below 30 active.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "$service:sql:pool:default:total{}",
     "legendFormat": "total/{{instance}}"
    },
    {
     "expr": "$service:sql:pool:default:active{}",
     "legendFormat": "active/{{instance}}"
    },
    {
     "expr": "$service:sql:pool:default:blocked{}",
     "legendFormat": "blocked/{{instance}}"
    }
   ]
  },
  {
   "title": "$service redis latency",
   "type": "graph",
   "description": "Ideal value: Below 100 ms.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(rate($service:redis:command:latency:sscan__count_total[1m])) / sum(rate($service:redis:command:latency:sscan__totalTime_total[1m]))",
     "legendFormat": "sscan"
    },
    {
     "expr": "sum(rate($service:redis:command:latency:mset__count_total[1m])) / sum(rate($service:redis:command:latency:mset__totalTime_total[1m]))",
     "legendFormat": "mset"
    },
    {
     "expr": "sum(rate($service:redis:command:latency:mget__count_total[1m])) / sum(rate($service:redis:command:latency:mget__totalTime_total[1m]))",
     "legendFormat": "mget"
    },
    {
     "expr": "sum(rate($service:redis:command:latency:hmget__count_total[1m])) / sum(rate($service:redis:command:latency:hmget__totalTime_total[1m]))",
     "legendFormat": "hmget"
    },
    {
     "expr": "sum(rate($service:redis:command:latency:hmset__count_total[1m])) / sum(rate($service:redis:command:latency:hmset__totalTime_total[1m]))",
     "legendFormat": "hmset"
    },
    {
     "expr": "sum(rate($service:redis:command:latency:del__count_total[1m])) / sum(rate($service:redis:command:latency:del__totalTime_total[1m]))",
     "legendFormat": "del"
    },
    {
     "expr": "sum(rate($service:redis:command:latency:hdel__count_total[1m])) / sum(rate($service:redis:command:latency:hdel__totalTime_total[1m]))",
     "legendFormat": "hdel"
    },
    {
     "expr": "sum(rate($service:redis:command:latency:set__count_total[1m])) / sum(rate($service:redis:command:latency:set__totalTime_total[1m]))",
     "legendFormat": "set"
    }
   ]
  }
 ]
}