kubernetes:
  accounts: []
  #  - kubeconfigFile: /kubeconfigfiles/kubeconfig
  #    name: agent-demo

clouddriver:
  grpc: spin-clouddriver-grpc:9091
  insecure: true

server:
  port: 8082
  
prometheus:
  enabled: true
  # port: 8008