kubernetes:
  accounts: 
  - serviceAccount: true
    name: account000
                
clouddriver:
  grpc: spin-clouddriver-grpc:9091
  insecure: true

server:
  port: 8082
  
prometheus:
  enabled: true
  # port: 8008

logging:
  level: debug
