apiVersion: apps/v1
kind: Deployment
metadata:
  name: armory-agent
spec:
  selector:
    matchLabels:
      app: armory-agent
      cluster: armory-agent
  template:
    spec:
      containers:
      - name: armory-agent
        volumeMounts:
        - mountPath: /kubeconfigfiles
          name: kubeconfig-secret
      volumes:
      - name: kubeconfig-secret
        secret:
          defaultMode: 420
          secretName: kubeconfig-secret
