apiVersion: builtin
kind: ReplacementTransformer
metadata:
  name: clouddriver-serviceaccount
replacements:
- source:
    kind: ServiceAccount
  targets:
  - select:
      kind: SpinnakerService
    fieldPaths:
    - spec.spinnakerConfig.service-settings.clouddriver.kubernetes.serviceAccountName