# This utility is useful when you are installing Spinnaker into a multi-tenant
# Kubernetes cluster and want to ensure that all service account related
# resources are unique.
#
# All you need to do is modify the `suffixName` field in this patch and use it
# as in the following example:
#
# -- kustommization.yml
# namespace: my-namespace
#
# components:
#   - targets/kubernetes/default
#
# transformations:
#   - utilities/unique-service-account.yml
#
# This would product the following resources:
#   - ServiceAccount: spin-sa-my-unique-name
#   - ClusterRoleBinding: spin-cluster-role-binding-my-unique-name
#   - ClusterRole: spin-cluster-role-my-unique-name
#   - Ensure that the service account name matches in the Kubernetes provider
#   for your SpinnakerService
apiVersion: builtin
kind: PrefixSuffixTransformer
metadata:
  name: suffix-service-account-resources
suffix: -daniela-dev
fieldSpecs:
  - kind: ServiceAccount
    path: metadata/name
  - kind: ClusterRole
    path: metadata/name
  - kind: ClusterRoleBinding
    path: metadata/name
