apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  spinnakerConfig:
    config:
      features:
        fiat: true
      security:
        authz:
          enabled: true
          groupMembership:
            service: EXTERNAL
    profiles:
      fiat:  ## see https://spinnaker.io/reference/architecture/authz_authn/authorization/ for additional parameters
        fiat: 
          admin:
            roles:
              - spin-admin      #Assign external group spin-admin to the Spinnaker administrator role
              ### Verify if your user has admin access with using the FIAT API:
              ### k exec deploy/spin-fiat -- wget --no-proxy -O /dev/stdout http://localhost:7003/authorize/[username]
              ### expect to see: `admin: true` in the returned payload
      # enable pipeline permissions: https://spinnaker.io/setup/security/authorization/pipeline-permissions/
      orca:
        tasks:
          useManagedServiceAccounts: true
#       # Enable this setting under core_config/patch-deck.yml
#       deck:
#         settings-local.js: |
#           window.spinnakerSettings.feature.managedServiceAccounts = true;
#
#      # Use thhis block if pipeline permissions had been configured with run-as-user previously
#      front50:                                   
#        migrations:                               
#          migrateToManagedServiceAccounts: true.  
