apiVersion: v1
kind: ConfigMap
metadata:
  name: kubesvc-config
  namespace: spin-agent
data:
  kubesvc.yaml: |
    kubernetes:
      accounts:
      - name: ${CLUSTER_NAME}
        serviceAccount: true
        serviceAccountName: spin-sa
        metrics: false
    clouddriver:
      grpc: ${GRPC_ADDR}
      insecure: true
    server:
      port: 8082
