apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - deployment.yaml

configMapGenerator:
  - name: agent-proxy-config
    files:
      - envoy.yaml

patchesStrategicMerge:
  - ./patch-spin-clouddriver-grpc.yaml